title: Sakib Noor
description: > # this means to ignore newlines until "baseurl:"
  Financial Analysis and Data Science Projects
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sakib9493.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sakib Noor # add your name
author-img: sakib_noor.jpeg # add your photo
about-author: I am a financial analyst and a data scientist. Always hungry to keep learning. # add description
social-twitter: Sakib9493Noor # add your Twitter handle
social-facebook: sakib.noor # add your Facebook handle
social-github: sakib9493 # add your Github handle
social-linkedin: sakibnoor # add your Linkedin handle
social-email: sakib9493@gmail.com # add your Email address

# Disqus
discus-identifier: sakibnoor # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
